import json
from pathlib import Path

from image_rebuild.cli import main, resolve_target_ref

FIXTURE = str(Path(__file__).parent / "fixtures" / "twistcli_sample.json")
TRIVY_FIXTURE = str(Path(__file__).parent / "fixtures" / "trivy_sample.json")


def test_version_flag(capsys):
    import pytest
    with pytest.raises(SystemExit) as exc:
        main(["--version"])
    assert exc.value.code == 0
    assert "image-rebuild" in capsys.readouterr().out


def test_scan_from_report(capsys):
    rc = main(["scan", "--report", FIXTURE])
    out = capsys.readouterr().out
    assert rc == 0
    assert "critical=2" in out
    assert "CVE-2024-0001" in out


def test_scan_fail_on_gate():
    assert main(["scan", "--report", FIXTURE, "--fail-on-gate"]) == 1


def test_fix_report_without_dry_run_is_rejected():
    # The live build+verify loop needs a real image, not an offline report.
    assert main(["fix", "--report", FIXTURE]) == 3


def test_fix_loop_requires_image():
    assert main(["fix"]) == 3


def test_fix_push_without_credentials_is_config_error(monkeypatch):
    for name in ("DOCKERHUB_USER", "DOCKERHUB_TOKEN", "REGISTRY_USER", "REGISTRY_TOKEN"):
        monkeypatch.delenv(name, raising=False)
    # --push with no registry credentials fails fast as a config error.
    assert main(["fix", "img:tag", "--push"]) == 3


def test_scan_trivy_report_autodetected(capsys):
    rc = main(["scan", "--report", TRIVY_FIXTURE])
    out = capsys.readouterr().out
    assert rc == 0
    assert "critical=3" in out
    assert "CVE-2024-0001" in out


def test_resolve_target_ref():
    assert resolve_target_ref("penpotapp/mcp:1.2", None) is None
    assert resolve_target_ref("penpotapp/mcp:1.2", "me/mcp") == "me/mcp:1.2"
    assert resolve_target_ref("penpotapp/mcp", "me/mcp") == "me/mcp:latest"
    assert resolve_target_ref("penpotapp/mcp:1.2", "me/mcp:v9") == "me/mcp:v9"
    assert (resolve_target_ref("nginx:1.25", "harbor.corp.com/patched/nginx")
            == "harbor.corp.com/patched/nginx:1.25")


def test_fix_dry_run_generates_dockerfile(tmp_path, capsys):
    out_file = tmp_path / "Dockerfile"
    # The sample has an unsupported java CVE, so the gate is not clearable -> rc 1.
    rc = main(["fix", "--report", FIXTURE, "--dry-run", "-o", str(out_file)])
    out = capsys.readouterr().out
    assert rc == 1
    assert "FROM example/app:1.0" in out
    assert out_file.read_text().startswith("# AUTOGENERATED")


def test_fix_dry_run_clean_when_all_fixable(tmp_path):
    raw = {
        "results": [{
            "name": "img:tag",
            "distro": "Debian GNU/Linux 11",
            "vulnerabilities": [
                {"id": "CVE-1", "severity": "critical", "packageName": "openssl",
                 "packageVersion": "1.1.1k-1", "status": "fixed in 1.1.1n",
                 "packageType": "os"},
            ],
        }]
    }
    report = tmp_path / "r.json"
    report.write_text(json.dumps(raw))
    assert main(["fix", "--report", str(report), "--dry-run"]) == 0
