import pytest

from image_rebuild.generator import generate_dockerfile
from image_rebuild.models import (
    PackageFix,
    RemediationChannel,
    RemediationPlan,
)


def _plan(channels):
    return RemediationPlan(
        image="example/app:1.0",
        base_image="example/app:1.0",
        os_manager="apt",
        channels=channels,
    )


def test_apt_and_pip_dockerfile():
    plan = _plan([
        RemediationChannel("apt", "os", [
            PackageFix("openssl", "1.1.1n-0+deb11u1", ["CVE-1"]),
            PackageFix("libxml2", "2.9.14", ["CVE-2"]),
        ]),
        RemediationChannel("pip", "python", [
            PackageFix("requests", "2.32.0", ["CVE-3"]),
        ]),
    ])
    df = generate_dockerfile(plan)
    assert df.startswith("# AUTOGENERATED")
    assert "FROM example/app:1.0" in df
    assert "USER root" in df
    assert "apt-get install -y --only-upgrade" in df
    assert "openssl=1.1.1n-0+deb11u1" in df
    assert 'pip install --no-cache-dir --upgrade' in df
    assert '"requests==2.32.0"' in df
    assert "rm -rf /var/lib/apt/lists/*" in df
    # every fixed CVE is referenced in an audit comment
    for cve in ("CVE-1", "CVE-2", "CVE-3"):
        assert cve in df


def test_apk_template():
    plan = _plan([RemediationChannel("apk", "os", [PackageFix("musl", "1.2.4-r2", ["CVE-9"])])])
    df = generate_dockerfile(plan)
    assert "apk add --no-cache --upgrade" in df
    assert "musl=1.2.4-r2" in df


def test_dnf_template():
    plan = _plan([RemediationChannel("dnf", "os", [PackageFix("glibc", "2.34-60", ["CVE-7"])])])
    df = generate_dockerfile(plan)
    assert "dnf install -y" in df
    assert "glibc-2.34-60" in df
    assert "dnf clean all" in df


def test_original_user_restored_when_known():
    plan = _plan([RemediationChannel("apt", "os", [PackageFix("p", "1", ["C"])])])
    assert "USER appuser" in generate_dockerfile(plan, original_user="appuser")
    assert "restore the image's original USER" in generate_dockerfile(plan)


def test_non_actionable_plan_raises():
    with pytest.raises(ValueError):
        generate_dockerfile(_plan([]))
