import json
from pathlib import Path

from image_rebuild.cli import main

FIXTURE = str(Path(__file__).parent / "fixtures" / "twistcli_sample.json")


def test_scan_from_report(capsys):
    rc = main(["scan", "--report", FIXTURE])
    out = capsys.readouterr().out
    assert rc == 0
    assert "critical=2" in out
    assert "CVE-2024-0001" in out


def test_scan_fail_on_gate():
    assert main(["scan", "--report", FIXTURE, "--fail-on-gate"]) == 1


def test_fix_report_without_dry_run_is_rejected():
    # The live build+verify loop needs a real image, not an offline report.
    assert main(["fix", "--report", FIXTURE]) == 3


def test_fix_loop_requires_image():
    assert main(["fix"]) == 3


def test_fix_push_not_yet_implemented():
    # --push (publishing) lands in M4.
    assert main(["fix", "img:tag", "--push"]) == 3


def test_fix_dry_run_generates_dockerfile(tmp_path, capsys):
    out_file = tmp_path / "Dockerfile"
    # The sample has an unsupported java CVE, so the gate is not clearable -> rc 1.
    rc = main(["fix", "--report", FIXTURE, "--dry-run", "-o", str(out_file)])
    out = capsys.readouterr().out
    assert rc == 1
    assert "FROM example/app:1.0" in out
    assert out_file.read_text().startswith("# AUTOGENERATED")


def test_fix_dry_run_clean_when_all_fixable(tmp_path):
    raw = {
        "results": [{
            "name": "img:tag",
            "distro": "Debian GNU/Linux 11",
            "vulnerabilities": [
                {"id": "CVE-1", "severity": "critical", "packageName": "openssl",
                 "packageVersion": "1.1.1k-1", "status": "fixed in 1.1.1n",
                 "packageType": "os"},
            ],
        }]
    }
    report = tmp_path / "r.json"
    report.write_text(json.dumps(raw))
    assert main(["fix", "--report", str(report), "--dry-run"]) == 0
