"""Render a RemediationPlan into a remediation Dockerfile.

The Dockerfile builds `FROM` the original image and layers targeted package
upgrades on top — no upstream Dockerfile required. Each RUN layer is annotated
with the CVEs it addresses for auditability.
"""

from __future__ import annotations

from .models import RemediationChannel, RemediationPlan

_HEADER = "# AUTOGENERATED by image-rebuild — do not edit by hand."


def _continuation(items: list[str], indent: str = "        ") -> str:
    """Join package specs as backslash-continued lines under a RUN."""
    return " \\\n".join(f"{indent}{item}" for item in items)


def _channel_block(channel: RemediationChannel) -> str:
    cves = sorted({cve for fix in channel.fixes for cve in fix.cves})
    comment = f"# {channel.ecosystem} via {channel.manager}: {', '.join(cves)}"

    if channel.manager == "apt":
        specs = [f"{f.package}={f.fixed}" for f in channel.fixes]
        run = (
            "RUN apt-get update && \\\n"
            "    apt-get install -y --only-upgrade \\\n"
            f"{_continuation(specs)} && \\\n"
            "    apt-get clean && rm -rf /var/lib/apt/lists/*"
        )
    elif channel.manager == "apk":
        specs = [f"{f.package}={f.fixed}" for f in channel.fixes]
        run = (
            "RUN apk add --no-cache --upgrade \\\n"
            f"{_continuation(specs)}"
        )
    elif channel.manager == "dnf":
        specs = [f"{f.package}-{f.fixed}" for f in channel.fixes]
        run = (
            "RUN dnf install -y \\\n"
            f"{_continuation(specs)} && \\\n"
            "    dnf clean all"
        )
    elif channel.manager == "pip":
        specs = [f'"{f.package}=={f.fixed}"' for f in channel.fixes]
        run = (
            "RUN pip install --no-cache-dir --upgrade \\\n"
            f"{_continuation(specs)}"
        )
    else:  # pragma: no cover - planner only emits the managers above
        raise ValueError(f"no Dockerfile template for manager '{channel.manager}'")

    return f"{comment}\n{run}"


def generate_dockerfile(plan: RemediationPlan, original_user: str | None = None) -> str:
    """Return the remediation Dockerfile text for an actionable plan."""
    if not plan.actionable:
        raise ValueError(
            "plan has no remediation channels; nothing to generate "
            "(check blockers/unsupported instead)."
        )

    lines: list[str] = [
        _HEADER,
        f"# Remediates {len(plan.fixed_cves)} CVE(s) in {plan.image}: "
        f"{', '.join(plan.fixed_cves)}",
        f"FROM {plan.base_image}",
        "",
        "# Pin the original image by digest in production for reproducible rebuilds.",
        "USER root",
        "",
    ]

    blocks = [_channel_block(c) for c in plan.channels]
    lines.append("\n\n".join(blocks))

    lines.append("")
    if original_user:
        lines.append(f"USER {original_user}")
    else:
        lines.append("# NOTE: restore the image's original USER here (resolved at build time).")

    return "\n".join(lines) + "\n"
